<?php echo $this->doctype(); ?>

<html>
    <head>
        <?php 
            echo $this->headTitle($this->title); 
            $this->headScript()->appendFile('//code.jquery.com/jquery.js');

            if (isset($this->searchPlugin) && $this->searchPlugin === true) {
                $this->headScript()->appendFile('/js/jquery.searchPlugin.js');
            }
            echo $this->headScript()->appendFile('/js/bootstrap.min.js');


            $this->headLink(array(
                'rel'  => 'favicon',
                'href' => '/images/favicon.ico',                
            ))->appendStylesheet('/css/bootstrap.min.css');
            $this->headLink()->appendStylesheet('/css/main.css');
            $this->headLink()->appendStylesheet('//fonts.googleapis.com/css?family=Hammersmith+One');
            echo $this->headLink();
        ?>
    </head>

    <body>
        <div id="all">
            <?php
         		echo $this->render("_globalHeader.phtml") . "\n";
         		echo $this->render("_globalBody.phtml") . "\n";
         	?>
        </div>
    </body>    
</html>