<div class="searchData">
	<div class="query"><?php echo $this->requestedQuery; ?></div>
	<img class="progressBar" src="/images/loading-dots.gif">
</div>
<div id="search">
	<div class="col">
	</div>
	<div class="col">
	</div>
</div>

<script>
    $(document).ready(function () {

        setTimeout(function(){
                $('#search').getSocialData();
            },
            3000
        );


    });
</script>